version: '3.1'
services:
  mongo:
    image: mongo:7
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: sageslate
      MONGO_INITDB_ROOT_PASSWORD: sageslatepassword
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://sageslate:sageslatepassword@mongo:27017/
    depends_on:
      - mongo
  redis:
    image: redis:7
    restart: on-failure
    ports:
      - '6379:6379'